apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-argocd-kustomize
  labels:
    app: golang-argocd-kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-argocd-kustomize
  template:
    metadata:
      labels:
        app: golang-argocd-kustomize
    spec:
      containers:
        - name: golang-argocd-kustomize
          image: 0054/golang-argocd-kustomize:fabd2a811bdbc47ec052bdd698f66995f9543710
          ports:
            - containerPort: 8080
